ui_print ""
ui_print "---------------------------"
ui_print ""
ui_print "OneUI Launcher Mods Overlay"
ui_print ""
ui_print "---------------------------"
ui_print ""
ui_print "   Installing overlay...   "
ui_print ""
ui_print "          ✓ Done           "
ui_print ""
ui_print "---------------------------"
ui_print ""
ui_print "Reboot your device to activate the hide apps"
ui_print "option in OneUI Launcher Mods."
ui_print ""
ui_print "You must keep this module installed for hide"
ui_print "apps to work."
ui_print ""